import 'package:safe_school_game/models/game.dart';

List<Game> appGames = [
  Game(
      url: 'https://simmer.io/@Pakqori/belajar-mengenali-bencana-diggo',
      title: "Sie Gemz",
      icon: "assets/images/kuki/kuki.png",
      image: "assets/images/kuki/kuki.png",
      author: "Achmad Mustofa and Team",
      description:
          "Pelajari macam-macam bencana melalui peta-peta yang menarik. Banyak keseruan yang dapat kamu rasakan dengan ilmu pengetahuan terkait bencana tentunya!",
      difficult: 4,
      educationContent: 3,
      shortInformation: "Apa aja deh",
      reference: "bla bla",
      images: [
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
      ]),
  Game(
      url: 'https://www.google.com',
      title: "Belajar Mengenali Bencana",
      icon: "assets/images/kuki/kuki.png",
      image: "assets/images/kuki/kuki.png",
      author: "Muhammad Alfikri / Diggo Team",
      description: "Permainan ini bertujuan untuk mengedukasi pemain dengan konsep belajar sambil bermain kuis edukasi. Dimana di dalam permainan ini terdapat gambaran tampulan, suara, penjelasan dan tindakan pada saat terjadi bencana.",
      difficult: 3,
      educationContent: 5,
      shortInformation: "ok deh",
      reference: "bla bla",
      images: [
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
      ]),
  Game(
      url: 'https://safeschoolgame.inahost.net/kuki/',
      title: "Bencana Alam",
      icon: "assets/images/kuki/kuki.png",
      image: "assets/images/kuki/kuki.png",
      author: "Prasista Nasya Zerlinda",
      description: "Pelajari macam-macam aja",
      difficult: 1,
      educationContent: 2.5,
      shortInformation: "sip coy",
      reference: "dasdmad",
      images: [
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
      ]),
  Game(
      url: 'https://safeschoolgame.inahost.net/covid19/',
      title: "Pengenalan COVID-19",
      icon: "assets/images/kuki/kuki.png",
      image: "assets/images/kuki/kuki.png",
      author: "Ahmad Mustofa",
      description: "Pelajari macam-macam aja",
      difficult: 1,
      educationContent: 2.5,
      shortInformation: "sip coy",
      reference: "dasdmad",
      images: [
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
      ]),
  Game(
      url: 'https://www.google.com',
      title: "Flappy Pirate Wow",
      icon: "assets/images/kuki/kuki.png",
      image: "assets/images/kuki/kuki.png",
      author: "Della Puspita Ramadhani",
      description: "Pelajari macam-macam aja",
      difficult: 1,
      educationContent: 2.5,
      shortInformation: "sip coy",
      reference: "dasdmad",
      images: [
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
        GameImages(images: "assets/images/kuki/kuki.png"),
      ]),
];
